### ISSUE TITLE
没有脑子怎么办

### ISSUE THREAD

**Issue by Mitpoppy** [wanan12138/RW-Launcher#1]

**Comment by wanan12138** [comment]
很好的问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wanan12138/RW-Launcher"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月6日(星期六) 下午3:08
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[wanan12138/RW-Launcher] 没有脑子怎么办 (Issue #1)
